version: "3.6"
services:

  adminerd:
    # http://192.168.88.64:5002/
    # http://10.4.1.231:6117/
    # image: adminer:4.7
    # image: dockette/adminer:full
    image: dgleba/adminer-sqlite:latest
    # build: ./adminer-sqlite
    restart: always
    ports:
      - 5002:80
      # 8080 for regular adminer, 80 for dockette
    volumes:
      - ../sysdata/kumadata:/bag
      # - ../sysdata/kumadata/kuma.db-shm:/dbs.sq3
      # - ../sysdata/kumadata/kuma.db-wal:/dbw.sq3
      #- ./adminer-sqlite:/var/www/html
    environment:
      - ADMINER_DEFAULT_SERVER=srvr
      - DB_PATH=/bag/kuma.db
      #- DB_PATH=/a/db.sq3
      - DB_USER=user
      - DB_PASS=apass
      # - ADMINER_PLUGINS='tables-filter'

