version: "3.6"
services:
  upkuma:
    # http://192.168.88.64:5001/
    image: louislam/uptime-kuma:1
    restart: always
    ports:
      - 5001:3001
    volumes:
      #- ../sysdata/kumadata:/app/data
      - ../sysdata/kumadata:/app/data

# volumes:
#   upkumadata: