version: "3.6"
services:
  py:
    # image: python:3.7
    build:
      context: .
      dockerfile: ./py.Dockerfile
    restart: always
    ports:
      - 8000:8000
    working_dir: /app
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    volumes:
      - ./:/app
      # use pip cache to reduce startup time..
      # https://stackoverflow.com/questions/25305788/how-to-avoid-reinstalling-packages-when-building-docker-image-for-python-project
      - $HOME/.cache/pip/:/root/.cache/pip
    #
    # this yields error - no module mysql..  command: pip install -r requirements.txt
    # command: sh -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    command: python manage.py runserver 0.0.0.0:8000
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "90"

  maria:
    # Adminer server address: 10.4.1.231:6306
    image: mariadb:10.4
    # restart: always
    env_file:
      - .env
    ports:
      - "6306:3306"
    volumes:
      - ../datasys/maria473/:/var/lib/mysql/ # folder for mysql's internal data files.
      - .:/root # folder for scripts, etc.
      - ../data/maria473/:/home # folder for exported data, etc.
    # networks:
    #   - sister
    # https://medium.freecodecamp.org/how-to-setup-log-rotation-for-a-docker-container-a508093912b2
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "90"
