# https://hub.docker.com/_/mysql
version: "3.6"

services:
  dbm:
    image: mysql:5.5
    #container_name: mysqldbm
    # build: .
    restart: always
    env_file:
      - .env
    # environment:
    # MYSQL_DATABASE: test
    # command: --default-authentication-plugin=mysql_native_password
    # https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_file_per_table
    command: --innodb-file-per-table=1
    ports:
      - "14307:3306"
    volumes:
      - ./sysdata/mysqldata:/var/lib/mysql/  # folder for mysql's internal data files.
      - .:/root # folder for scripts, etc.
      - ./data/home/:/home # folder for exported data, etc.
      - ./sysdata/in-out/:/in-out # folder for exported data, etc.
    # networks:
    #   - sister2
    # https://medium.freecodecamp.org/how-to-setup-log-rotation-for-a-docker-container-a508093912b2
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "3"

  adminer:
    # 10.4.1.231:6117/  use db or 10.4.1.228:3308 for server while logging in.
    image: adminer:4.7
    restart: always
    ports:
      - 14117:8080
    # networks:
    #   - sister2

