version: "3.6"
services:
  deb:
    # image: python:3.7
    build:
      context: .
      dockerfile: ./deb.Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    # this yields error - no module mysql..  command: pip install -r requirements.txt
    # command: sh -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    # command: python manage.py runserver 0.0.0.0:8000
    #
    # restart: always
    # ports:
    #   - 8000:8000
    # environment:
    #   PYTHONUNBUFFERED: 1
#
