version: "3.6"
services:
  sqlpad:
    # 192.168.88.60:6153
    image: sqlpad/sqlpad:3.2.1
    restart: always
    env_file:
      - .env
    ports:
      - "6153:3000"
    volumes:
      - sqlpadv:/var/lib/sqlpad

volumes:
  sqlpadv:
