# ref..
# https://gist.github.com/satendra02/1b335b06bfc5921df486f26bd98e0e89
# https://www.reddit.com/r/docker/comments/7zjbe4/docker_rails_puma_nginx_postgres/
# https://itnext.io/docker-rails-puma-nginx-postgres-999cd8866b18

version: "3.6"

services:

  # web:
  #   build:
  #     context: .
  #     dockerfile: ./docker/app.Dockerfile
  #     args:
  #       - RACK_ENV=development
  #       - RAKE_ENV=development
  #       - RAILS_ENV=development
  #   working_dir: /app
  #   volumes:
  #     - ./apprails:/app
  #   environment:
  #     - RACK_ENV=development
  #     - RAKE_ENV=development
  #     - RAILS_ENV=development
  #   ports:
  #     - 16123:3000
  #   command: bundle exec rails s -p 3000 -b '0.0.0.0'



  adminerd:
    # 10.4.1.231:6117/
    
    # image: adminer:4.7
    # image: dockette/adminer:full

    # image from hub. built from the line below....  image: dgleba/adminer-sqlite:one
    build: ./adminer-sqlite    
    restart: always
    ports:
      - 16134:80
      # 8080 for regular adminer, 80 for dockette
    volumes:
      - ./apprails/db/development.sqlite3:/db.sq3
      #- ./adminer-sqlite:/var/www/html
    environment:
      - ADMINER_DEFAULT_SERVER=srvr
      - DB_PATH=/db.sq3
      - DB_USER=user
      - DB_PASS=abc
      # - ADMINER_PLUGINS='tables-filter'


# volumes:
#   bundle_cache:
